/**
 * This file is AUTO GENERATED by [msw-auto-mock](https://github.com/zoubingwu/msw-auto-mock)
 * Feel free to commit/edit it as you need.
 */
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import { HttpResponse, http } from "msw";
import { faker } from "@faker-js/faker";

faker.seed(1);

const baseURL = "http://localhost:5101";
const MAX_ARRAY_LENGTH = 5;

// Map to store counters for each API endpoint
const apiCounters = new Map<string, number>();

const next = (apiKey: string) => {
  let currentCount = apiCounters.get(apiKey) ?? 0;
  if (currentCount === Number.MAX_SAFE_INTEGER - 1) {
    currentCount = 0;
  }
  apiCounters.set(apiKey, currentCount + 1);
  return currentCount;
};

export const handlers = [
  http.get(`${baseURL}/categories`, async () => {
    const resultArray = [[getGetCategories200Response(), { status: 200 }]] as [
      any,
      { status: number },
    ][];

    return HttpResponse.json(
      ...resultArray[next(`get /categories`) % resultArray.length],
    );
  }),
  http.post(`${baseURL}/categories`, async () => {
    const resultArray = [[getPostCategories201Response(), { status: 201 }]] as [
      any,
      { status: number },
    ][];

    return HttpResponse.json(
      ...resultArray[next(`post /categories`) % resultArray.length],
    );
  }),
  http.get(`${baseURL}/categories/:id`, async () => {
    const resultArray = [
      [getGetCategoriesId200Response(), { status: 200 }],
    ] as [any, { status: number }][];

    return HttpResponse.json(
      ...resultArray[next(`get /categories/:id`) % resultArray.length],
    );
  }),
  http.put(`${baseURL}/categories/:id`, async () => {
    const resultArray = [
      [getPutCategoriesId200Response(), { status: 200 }],
    ] as [any, { status: number }][];

    return HttpResponse.json(
      ...resultArray[next(`put /categories/:id`) % resultArray.length],
    );
  }),
  http.delete(`${baseURL}/categories/:id`, async () => {
    const resultArray = [
      [getDeleteCategoriesId200Response(), { status: 200 }],
    ] as [any, { status: number }][];

    return HttpResponse.json(
      ...resultArray[next(`delete /categories/:id`) % resultArray.length],
    );
  }),
  http.get(`${baseURL}/recipes`, async () => {
    const resultArray = [[getGetRecipes200Response(), { status: 200 }]] as [
      any,
      { status: number },
    ][];

    return HttpResponse.json(
      ...resultArray[next(`get /recipes`) % resultArray.length],
    );
  }),
  http.post(`${baseURL}/recipes`, async ({ request }) => {
    const resultArray = [[getPostRecipes201Response(), { status: 201 }]] as [
      any,
      { status: number },
    ][];

    return HttpResponse.json(
      ...resultArray[next(`post /recipes`) % resultArray.length],
    );
  }),
  http.get(`${baseURL}/recipes/:id`, async () => {
    const resultArray = [[getGetRecipesId200Response(), { status: 200 }]] as [
      any,
      { status: number },
    ][];

    return HttpResponse.json(
      ...resultArray[next(`get /recipes/:id`) % resultArray.length],
    );
  }),
  http.put(`${baseURL}/recipes/:id`, async () => {
    const resultArray = [[getPutRecipesId200Response(), { status: 200 }]] as [
      any,
      { status: number },
    ][];

    return HttpResponse.json(
      ...resultArray[next(`put /recipes/:id`) % resultArray.length],
    );
  }),
  http.delete(`${baseURL}/recipes/:id`, async () => {
    const resultArray = [
      [getDeleteRecipesId200Response(), { status: 200 }],
    ] as [any, { status: number }][];

    return HttpResponse.json(
      ...resultArray[next(`delete /recipes/:id`) % resultArray.length],
    );
  }),
];

export function getGetCategories200Response() {
  return [
    ...new Array(faker.number.int({ min: 1, max: MAX_ARRAY_LENGTH })).keys(),
  ].map((_) => ({
    id: faker.number.int(),
    name: faker.person.fullName(),
  }));
}

export function getPostCategories201Response() {
  return {
    id: faker.number.int(),
    name: faker.person.fullName(),
  };
}

export function getGetCategoriesId200Response() {
  return {
    id: faker.number.int(),
    name: faker.person.fullName(),
  };
}

export function getPutCategoriesId200Response() {
  return {
    id: faker.number.int(),
    name: faker.person.fullName(),
  };
}

export function getDeleteCategoriesId200Response() {
  return faker.datatype.boolean();
}

export function getGetRecipes200Response() {
  return [
    ...new Array(faker.number.int({ min: 1, max: MAX_ARRAY_LENGTH })).keys(),
  ].map((_) => ({
    id: faker.number.int(),
    title: faker.lorem.words(),
    ingredients: [
      ...new Array(faker.number.int({ min: 1, max: MAX_ARRAY_LENGTH })).keys(),
    ].map((_) => faker.lorem.words()),
    instructions: faker.lorem.words(),
    categories: [
      ...new Array(faker.number.int({ min: 1, max: MAX_ARRAY_LENGTH })).keys(),
    ].map((_) => faker.number.int()),
  }));
}

export function getPostRecipes201Response() {
  return {
    id: faker.number.int(),
    title: faker.lorem.words(),
    ingredients: [
      ...new Array(faker.number.int({ min: 1, max: MAX_ARRAY_LENGTH })).keys(),
    ].map((_) => faker.lorem.words()),
    instructions: faker.lorem.words(),
    categories: [
      ...new Array(faker.number.int({ min: 1, max: MAX_ARRAY_LENGTH })).keys(),
    ].map((_) => faker.number.int()),
  };
}

export function getGetRecipesId200Response() {
  return {
    id: faker.number.int(),
    title: faker.lorem.words(),
    ingredients: [
      ...new Array(faker.number.int({ min: 1, max: MAX_ARRAY_LENGTH })).keys(),
    ].map((_) => faker.lorem.words()),
    instructions: faker.lorem.words(),
    categories: [
      ...new Array(faker.number.int({ min: 1, max: MAX_ARRAY_LENGTH })).keys(),
    ].map((_) => faker.number.int()),
  };
}

export function getPutRecipesId200Response() {
  return {
    id: faker.number.int(),
    title: faker.lorem.words(),
    ingredients: [
      ...new Array(faker.number.int({ min: 1, max: MAX_ARRAY_LENGTH })).keys(),
    ].map((_) => faker.lorem.words()),
    instructions: faker.lorem.words(),
    categories: [
      ...new Array(faker.number.int({ min: 1, max: MAX_ARRAY_LENGTH })).keys(),
    ].map((_) => faker.number.int()),
  };
}

export function getDeleteRecipesId200Response() {
  return faker.datatype.boolean();
}
