/**
 * This file is AUTO GENERATED by [msw-auto-mock](https://github.com/zoubingwu/msw-auto-mock)
 * Feel free to commit/edit it as you need.
 */
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import { HttpHandler, HttpResponse, http } from "msw";
import { faker } from "@faker-js/faker";

faker.seed(1);

const baseURL = "http://localhost:5101";
const MAX_ARRAY_LENGTH = 5;

// Map to store counters for each API endpoint
const apiCounters = new Map<string, number>();

const next = (apiKey: string) => {
    let currentCount = apiCounters.get(apiKey) ?? 0;
    if (currentCount === Number.MAX_SAFE_INTEGER - 1) {
        currentCount = 0;
    }
    apiCounters.set(apiKey, currentCount + 1);
    return currentCount;
};

export const overrideHandlers = [
    http.post(`${baseURL}/recipes`, async ({ request }) => {
        const requestBody = await request.json();
        const response = requestBody as Record<string, unknown>;
        response.id = faker.number.int();

        return HttpResponse.json(response);
    }),
    http.put(`${baseURL}/recipes/:id`, async ({ request }) => {
        const requestBody = await request.json();
        const response = requestBody as Record<string, unknown>;
        response.categories
        return HttpResponse.json(response);
    }),
    http.post(`${baseURL}/categories`, async ({ request }) => {
        const requestBody = await request.json();
        const response = requestBody as Record<string, unknown>;
        response.id = faker.number.int();

        return HttpResponse.json(response);
    })

]

export const recipeGet404: HttpHandler = http.get(`${baseURL}/recipes`, async () => {
    return HttpResponse.json({ error: "HTTP 404 Not Found" }, { status: 404 })
}, { once: true }),

export const recipePost404: HttpHandler = http.post(`${baseURL}/recipes`, async () => {
    return HttpResponse.json({ error: "HTTP 404 Not Found" }, { status: 404 })
}, { once: true }),

export const recipePut404: HttpHandler = http.put(`${baseURL}/recipes/*`, async () => {
    return HttpResponse.json({ error: "HTTP 404 Not Found" }, { status: 404 })
}, { once: true }),

export const recipeDelete404: HttpHandler = http.delete(`${baseURL}/recipes/*`, async () => {
    return HttpResponse.json({ error: "HTTP 404 Not Found" }, { status: 404 })
}, { once: true }),